import { Router } from "express";
import prisma from "../db/primsa.client";
import AuthController from "../controllers/auth.controller";
import AuthService from "../services/auth.service";
import verifyJwt from "../middlewares/auth.middleware";
const router = Router();
const controller = new AuthController(new AuthService(prisma));
router.route("/login").post(controller.login);
router.route("/logout").get(verifyJwt,controller.logout);
router.route("/profile").get(verifyJwt,controller.getProfile);
router.route("/verify-account").get(controller.verifyEmail);
router.route("/get-verification-link").post(controller.getVerificationMail);
router.route("/reset-password-link").post(controller.getResetPasswordLink);
router.route("/reset-password").patch(verifyJwt,controller.resetPassword);
router.route("/current-user").get(verifyJwt,controller.getCurrentUser);
router.route("/refresh").get(controller.refreshUser);
export default router;
